### ISSUE TITLE
npm start error

### ISSUE THREAD

**Issue by patelpratyush** [mayankagarwal09/dev-portfolio#14]
when i typed npm start it returned this.

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:138:10)
    at module.exports (/Users/pratyush/dev-portfolio/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/pratyush/dev-portfolio/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/Users/pratyush/dev-portfolio/node_modules/webpack/lib/NormalModule.js:471:10)
    at /Users/pratyush/dev-portfolio/node_modules/webpack/lib/NormalModule.js:503:5
    at /Users/pratyush/dev-portfolio/node_modules/webpack/lib/NormalModule.js:358:12
    at /Users/pratyush/dev-portfolio/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/pratyush/dev-portfolio/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/Users/pratyush/dev-portfolio/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
/Users/pratyush/dev-portfolio/node_modules/react-scripts/scripts/start.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:138:10)
    at module.exports (/Users/pratyush/dev-portfolio/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/pratyush/dev-portfolio/node_modules/webpack/lib/NormalModule.js:417:16)
    at /Users/pratyush/dev-portfolio/node_modules/webpack/lib/NormalModule.js:452:10
    at /Users/pratyush/dev-portfolio/node_modules/webpack/lib/NormalModule.js:323:13
    at /Users/pratyush/dev-portfolio/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/pratyush/dev-portfolio/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/Users/pratyush/dev-portfolio/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /Users/pratyush/dev-portfolio/node_modules/babel-loader/lib/index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v20.5.0

**Comment by Yassin-Aru** [comment]
what do u get if you type:
```bash
npm i
```
inside of the root directory?

**Comment by patelpratyush** [comment]
npm i
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: react-chrono@1.22.0
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.2" from the root project
npm ERR!   peer react@"^16.8.0 || ^17.0.0-rc.1 || ^18.0.0" from @react-aria/ssr@3.7.0
npm ERR!   node_modules/@react-aria/ssr
npm ERR!     @react-aria/ssr@"^3.5.0" from @restart/ui@1.6.6
npm ERR!     node_modules/@restart/ui
npm ERR!       @restart/ui@"^1.6.3" from react-bootstrap@2.8.0
npm ERR!       node_modules/react-bootstrap
npm ERR!         react-bootstrap@"^2.0.0-rc.0" from the root project
npm ERR!   20 more (@restart/hooks, @restart/ui, uncontrollable, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^18.1.0" from react-chrono@1.22.0
npm ERR! node_modules/react-chrono
npm ERR!   react-chrono@"^1.12.1" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: react@18.2.0
npm ERR! node_modules/react
npm ERR!   peer react@"^18.1.0" from react-chrono@1.22.0
npm ERR!   node_modules/react-chrono
npm ERR!     react-chrono@"^1.12.1" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR!
npm ERR! For a full report see:
npm ERR! /Users/pratyush/.npm/_logs/2023-08-02T19_17_31_453Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: /Users/pratyush/.npm/_logs/2023-08-02T19_17_31_453Z-debug-0.log

**Comment by Yassin-Aru** [comment]
okay I think u need to use another different version of node because you are now running on v 20.X.X, u can use **nvm** for that, I think this will help

**Comment by Yassin-Aru** [comment]
or u need to update all of used packages, I will clone the repo and see if there is anything that I can do ...

**Comment by Yassin-Aru** [comment]
try this if it will work for 
```bash
npm update --force
```

**Comment by patelpratyush** [comment]
I reclone the repo and did the steps listed and it still gave the error after I typed
```
npm start
``` 

then I tried 
```
npm update --force
``` 

i still got 

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:138:10)
    at module.exports (/Users/pratyush/Desktop/dev-portfolio/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/pratyush/Desktop/dev-portfolio/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/Users/pratyush/Desktop/dev-portfolio/node_modules/webpack/lib/NormalModule.js:471:10)
    at /Users/pratyush/Desktop/dev-portfolio/node_modules/webpack/lib/NormalModule.js:503:5
    at /Users/pratyush/Desktop/dev-portfolio/node_modules/webpack/lib/NormalModule.js:358:12
    at /Users/pratyush/Desktop/dev-portfolio/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/pratyush/Desktop/dev-portfolio/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/Users/pratyush/Desktop/dev-portfolio/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
/Users/pratyush/Desktop/dev-portfolio/node_modules/react-scripts/scripts/start.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:138:10)
    at module.exports (/Users/pratyush/Desktop/dev-portfolio/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/pratyush/Desktop/dev-portfolio/node_modules/webpack/lib/NormalModule.js:417:16)
    at /Users/pratyush/Desktop/dev-portfolio/node_modules/webpack/lib/NormalModule.js:452:10
    at /Users/pratyush/Desktop/dev-portfolio/node_modules/webpack/lib/NormalModule.js:323:13
    at /Users/pratyush/Desktop/dev-portfolio/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/pratyush/Desktop/dev-portfolio/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/Users/pratyush/Desktop/dev-portfolio/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /Users/pratyush/Desktop/dev-portfolio/node_modules/babel-loader/lib/index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v20.5.0

**Comment by dylanroets** [comment]
In your package.json: change this line

"start": "react-scripts start"

to

"start": "react-scripts --openssl-legacy-provider start"



I believe this will run the older legacy version of node 16ish
